let dark = false 
let generator = [
    "You're amazing!",
    "Your creativity knows no bounds!",
    "You're a true inspiration!",
    "You light up the room!",
    "Your positivity is contagious!",
    "You have an incredible sense of style!",
    "You're a natural leader!",
    "Your smile can brighten anyone's day!",
    "You're so talented!",
    "You have a heart of gold!",
    "Your intelligence is impressive!",
    "You have a unique perspective on things!",
    "You're a joy to be around!",
    "Your kindness makes the world a better place!",
    "You always know how to make people feel special!",
    "You're a great listener!",
    "You have a wonderful sense of humor!",
    "Your determination is inspiring!",
    "You're one of a kind!",
    "You have a fantastic ability to uplift others!",
    "Your passion is truly admirable!",
    "You're so thoughtful!",
    "You have a beautiful soul!",
    "You radiate positivity!",
    "Your laughter is infectious!",
    "You're exceptionally bright!",
    "You bring out the best in people!",
    "You have a unique gift for making others feel valued!",
    "Your insight is always spot on!",
    "You handle challenges with grace!",
    "You're a breath of fresh air!",
    "Your enthusiasm is truly motivating!",
    "You're incredibly resourceful!",
    "You have an amazing work ethic!",
    "You're a great friend!",
    "You have a fantastic eye for detail!",
    "Your presence is calming!",
    "You inspire others to be their best selves!",
    "You're a treasure!",
    "Your ideas are brilliant!",
    "You have a knack for finding the silver lining!",
    "You're so encouraging!",
    "Your energy is contagious!",
    "You have a heart full of compassion!",
    "You're incredibly wise!",
    "Your positivity lights up the darkest days!",
    "You're a true gem!",
    "You have a magnetic personality!",
    "You're so reliable!",
    "You bring joy to everyone around you!",
    "Your courage is inspiring!",
    "You're a master at what you do!",
    "You make the world a better place!",
    "Your laughter brings happiness!",
    "You're a fantastic communicator!",
    "You have a wonderful imagination!",
    "You're a ray of sunshine!",
    "Your generosity knows no bounds!",
    "You're so adaptable!",
    "You have a talent for bringing people together!",
    "You're an amazing storyteller!",
    "You shine bright like a star!",
    "Your optimism is refreshing!",
    "You're incredibly humble!",
    "You have a gift for making others feel at ease!",
    "You're an outstanding problem solver!",
    "Your attention to detail is remarkable!",
    "You're a true friend!",
    "You have a unique charm!",
    "You're always so well-prepared!",
    "Your curiosity is inspiring!",
    "You're so genuine!",
    "You have an incredible ability to empathize!",
    "You're a wonderful role model!",
    "Your spirit is unbreakable!",
    "You're incredibly innovative!",
    "You have a knack for finding solutions!",
    "You're a beautiful person inside and out!",
    "Your strength is admirable!",
    "You're always full of great ideas!",
    "You have a fantastic sense of humor!",
    "You're an excellent team player!",
    "Your kindness is heartwarming!",
    "You're so fun to be around!",
    "You have a great perspective on life!",
    "You're so insightful!",
    "Your determination is unmatched!",
    "You're a champion for others!",
    "You have a warm and welcoming nature!",
    "You're a true visionary!",
    "Your perseverance is inspiring!",
    "You always know the right thing to say!",
    "You're a beacon of hope!",
    "Your grace under pressure is impressive!",
    "You have a fantastic ability to connect with others!",
    "You're so approachable!",
    "You make everyone feel included!",
    "Your dedication is remarkable!",
    "You're a fantastic motivator!",
    "You have a wonderful sense of adventure!",
    "You're an amazing thinker!",
    "Your friendship is a gift!",
    "You have a lovely personality!",
    "You're always learning and growing!",
    "You spread positivity wherever you go!",
    "You're so supportive!",
    "Your creativity is a breath of fresh air!",
    "You inspire others with your words!",
    "You're incredibly thoughtful!",
    "You have a fantastic ability to adapt!",
    "You're so generous with your time!",
    "You have a wonderful heart!",
    "You're an incredible mentor!",
    "Your love for life is infectious!",
    "You're a source of strength for many!",
    "You have a remarkable sense of empathy!",
    "You're a true advocate for others!",
    "Your presence is uplifting!",
    "You have a talent for finding joy in the little things!",
    "You're so encouraging to everyone!",
    "You have a great sense of balance in life!",
    "You're a wonderful problem solver!",
    "Your kindness is truly impactful!",
    "You bring so much to the table!",
    "You're always striving for excellence!",
    "You have a vibrant personality!",
    "You're a true asset to any team!",
    "Your vision is inspiring!",
    "You're so respectful of others!",
    "You have a great sense of timing!",
    "You're a fantastic conversationalist!",
    "You have a unique ability to see the big picture!",
    "You're always so understanding!",
    "Your presence makes everything better!",
    "You're incredibly loyal!",
    "You have an amazing ability to focus!",
    "You're a true champion of your values!",
    "Your compassion knows no limits!",
    "You have an incredible zest for life!",
    "You're so insightful about human nature!",
    "You have a way of making people feel heard!",
    "You're a great source of inspiration!",
    "You have a magnetic charm!",
    "You're so brave in facing challenges!",
    "Your laughter is a gift!",
    "You have an amazing ability to teach others!",
    "You're a wonderful collaborator!",
    "You bring a unique perspective to every discussion!",
    "You're always striving to improve!",
    "Your kindness touches hearts!",
    "You're so optimistic about the future!",
    "You have a talent for lifting spirits!",
    "You're an incredible supporter!",
    "Your vision for the future is inspiring!",
    "You always know how to make others laugh!",
    "You're so dedicated to your goals!",
    "Your joy is contagious!",
    "You're a fantastic friend to have!",
    "You have a natural ability to lead!",
    "You're so quick to offer help!",
    "You have a way of making challenges seem easy!",
    "You're a true pioneer!",
    "You have an incredible capacity for love!",
    "You're a light in the lives of many!",
    "Your presence is always a blessing!",
    "You have an unwavering spirit!",
    "You're so patient with everyone!",
    "You bring warmth wherever you go!",
    "Your intelligence shines through!",
    "You're a master at balancing work and play!",
    "You have a heart full of gratitude!",
    "You're a wonderful soul!",
    "Your resilience is inspiring!",
    "You're a shining example for others!",
    "You have a special gift for storytelling!",
    "You're always ready to lend a hand!",
    "Your kindness is like a warm hug!",
    "You inspire trust in everyone around you!",
    "You have a great sense of adventure!",
    "You're incredibly insightful about the world!",
    "You're a blessing to know!",
    "You have a remarkable ability to motivate others!",
    "You're a shining star!",
    "You bring out the best in every situation!",
    "You're so adaptable to change!",
    "Your sense of humor brightens the day!",
    "You have an amazing ability to forgive!",
    "You're a true friend in every sense!",
    "Your joy for life is infectious!",
    "You're so nurturing!",
    "You make everyone feel special!",
    "You're a source of wisdom!",
    "You have an incredible gift for listening!",
    "You're so enthusiastic about your passions!",
    "You have an unshakeable spirit!",
    "You're always ready to take on new challenges!",
    "You have a heart full of love!",
    "You're so great at creating connections!",
    "You have a unique perspective that is always refreshing!",
    "You inspire others with your courage!",
    "You're a fantastic role model!",
    "You have a brilliant mind!",
    "You're so dedicated to your passions!",
    "You have an incredible knack for problem-solving!",
    "You make every moment brighter!",
    "You're a natural at bringing people together!",
    "You have a beautiful way of expressing yourself!",
    "You're a wonderful source of comfort!",
    "You bring creativity to everything you do!",
    "You have a heart that understands!",
    "You're so resourceful in tough situations!",
    "You have an incredible ability to create change!",
    "You're always there when needed!",
    "You inspire others to follow their dreams!",
    "You have a way of seeing the good in everyone!",
    "You're so great at making others feel included!",
    "You have a positive impact on everyone you meet!",
    "You're a wonderful storyteller!",
    "You have an amazing ability to uplift spirits!",
    "You're so passionate about helping others!",
    "You have an incredible ability to express empathy!",
    "You're always so open-minded!",
    "You have a great sense of direction in life!",
    "You're so skilled at navigating challenges!",
    "You bring wisdom to every conversation!",
    "You're so skilled at turning ideas into action!",
    "You have a heart that never stops giving!",
    "You're always ready to embrace change!",
    "You inspire others to think outside the box!",
    "You have a fantastic ability to inspire others!",
    "You're so full of life!",
    "You have a unique way of making everyone feel welcome!",
    "You're so skilled at bringing joy to others!",
    "You have a beautiful perspective on the world!",
    "You're always so patient with yourself and others!",
    "You have an extraordinary ability to adapt!",
    "You're so great at making everyone feel valued!",
    "You have a way of lighting up the room!",
    "You're an amazing support system!",
    "You have a talent for making the mundane magical!",
    "You're so committed to personal growth!",
    "You have a wonderful ability to inspire laughter!",
    "You're always a breath of fresh air!",
    "You have a unique ability to see beauty in everything!",
    "You're so wonderful at bringing positivity!",
    "You inspire confidence in those around you!",
    "You have an incredible way of lifting others up!",
    "You're so skilled at fostering teamwork!",
    "You have a way of making every day brighter!",
    "You're a wonderful source of inspiration!",
    "You have an amazing ability to cultivate happiness!",
    "You're so quick to find joy in every moment!",
    "You have a remarkable talent for connecting with others!",
    "You're so diligent in pursuing your dreams!",
    "You have a beautiful way of showing compassion!",
    "You're a true advocate for kindness!",
    "You inspire creativity in others!",
    "You have a natural ability to see the good!",
    "You're so full of wisdom!",
    "You have a remarkable gift for storytelling!",
    "You're always a source of strength for others!",
    "You have a fantastic way of nurturing talent!",
    "You're so dedicated to making a difference!",
    "You have a heart that understands everyone!",
    "You bring out the potential in others!",
    "You're so passionate about your beliefs!",
    "You have an incredible way of making people feel at home!",
    "You're a true champion for those in need!",
    "You have a beautiful way of expressing gratitude!",
    "You're so skilled at creating a positive environment!",
    "You have a fantastic ability to inspire teamwork!",
    "You're so insightful about people's feelings!",
    "You bring comfort and joy to those around you!",
    "You're an incredible force for good!",
    "You have an extraordinary capacity for love and compassion!",
    "You're so great at finding joy in every challenge!",
    "You inspire people to believe in themselves!",
    "You have a remarkable ability to encourage growth!",
    "You're so thoughtful in your actions!",
    "You have a beautiful spirit!",
    "You're always there to offer support!",
    "You have an amazing ability to spread joy!",
    "You're a true friend to everyone!",
    "You bring laughter to every situation!",
    "You have a gift for nurturing relationships!",
    "You're so great at creating a sense of belonging!",
    "You have a wonderful ability to inspire hope!",
    "You're so committed to helping others succeed!",
    "You have a unique way of making others feel understood!",
    "You're always ready to lend an ear!",
    "You inspire collaboration in every group!",
    "You have an amazing ability to see potential in others!",
    "You're so wonderful at fostering creativity!",
    "You have a beautiful way of uplifting those around you!",
    "You're always so encouraging to everyone!",
    "You have a fantastic sense of adventure!",
    "You inspire everyone with your determination!",
    "You're a true friend and confidant!",
    "You have an incredible gift for bringing out the best in others!",
    "You're so great at creating lasting memories!",
    "You have a remarkable ability to inspire change!",
    "You're always so kind-hearted!",
    "You have a unique ability to lift spirits!",
    "You're so wonderful at making connections!",
    "You inspire others to reach for the stars!",
    "You're a true beacon of light in the world!",
    "You have a special talent for making others smile!",
    "You're incredibly dedicated to your values!",
    "You have a wonderful way of showing appreciation!",
    "You're a remarkable source of positivity!",
    "You bring enthusiasm to every project!",
    "You're so good at making others feel special!",
    "You have a unique ability to spread happiness!",
    "You're always ready to share your wisdom!",
    "You have a remarkable way of making people feel valued!",
    "You're a true gem in the lives of many!",
    "You have an incredible ability to inspire action!",
    "You're always so thoughtful and considerate!",
    "You bring joy to every moment!",
    "You're so fantastic at building relationships!",
    "You have a wonderful ability to foster creativity!",
    "You're a source of strength for everyone!",
    "You have a unique perspective that enriches discussions!",
    "You're so encouraging to those around you!",
    "You inspire others with your kindness!",
    "You have a natural ability to see beauty in everyone!",
    "You're an incredible source of inspiration!",
    "You have a fantastic way of bringing people together!",
    "You're so warm and inviting!",
    "You have a special talent for making people feel at ease!",
    "You're always striving to be your best self!",
    "You have a beautiful way of expressing love!",
    "You're a fantastic role model for others!",
    "You bring light to even the darkest days!",
    "You have a wonderful ability to inspire others to dream!",
    "You're so great at creating a sense of community!",
    "You have a heart that embraces everyone!",
    "You're an amazing source of support!",
    "You have a remarkable gift for helping others grow!",
    "You're always a source of encouragement!",
    "You have a unique ability to see the good in every situation!",
    "You're so dedicated to making a positive impact!",
    "You inspire everyone around you!",
    "You have a beautiful way of lifting others up!",
    "You're a wonderful person to know!",
    "You have an incredible way of turning challenges into opportunities!",
    "You're always so patient and understanding!",
    "You inspire trust in everyone you meet!",
    "You have a remarkable talent for creating joy!",
    "You're so great at nurturing relationships!",
    "You have an extraordinary capacity for kindness!",
    "You're always ready to help others shine!",
    "You have a unique way of making every day special!",
    "You're a true advocate for positivity!",
    "You inspire others to follow their passions!",
    "You have a beautiful way of connecting with people!",
    "You're always a breath of fresh air!",
    "You have a remarkable ability to empathize!",
    "You're so dedicated to your community!",
    "You have a wonderful talent for storytelling!",
    "You're an incredible force for positivity!",
    "You inspire everyone with your courage and strength!",
    "You have a unique ability to make every moment matter!",
    "You're so wonderful at making people feel welcome!",
    "You have an amazing ability to foster collaboration!",
    "You're a true light in the lives of many!",
    "You bring joy and laughter wherever you go!",
    "You have an incredible gift for making people feel special!",
    "You're always ready to embrace new experiences!",
    "You have a beautiful spirit that shines through!",
    "You're so thoughtful and caring!",
    "You inspire confidence in those around you!",
    "You have a remarkable ability to bring out the best in others!",
    "You're a source of inspiration for everyone you meet!",
    "You have a unique talent for making people feel valued!",
    "You're always so encouraging and supportive!",
    "You have a wonderful way of showing appreciation!",
    "You're a fantastic role model for kindness!",
    "You inspire others with your positive outlook!",
    "You have a beautiful way of expressing gratitude!",
    "You're a true champion for those in need!",
    "You have an incredible ability to inspire change!",
    "You're always ready to lift others up!",
    "You have a special talent for making people feel at home!",
    "You're so passionate about your dreams!",
    "You bring a unique perspective to every conversation!",
    "You're always so encouraging to those around you!",
    "You have a remarkable gift for making connections!",
    "You're an amazing source of support and encouragement!",
    "You inspire others to be their best selves!",
    "You have a beautiful heart!",
    "You're always ready to help those in need!",
    "You have a unique ability to see potential in everyone!",
    "You're so skilled at fostering teamwork!",
    "You have a wonderful way of uplifting spirits!",
    "You're an incredible friend and confidant!",
    "You bring positivity to every situation!",
    "You have a remarkable ability to create joy!",
    "You're so great at making others feel included!",
    "You have a talent for inspiring others!",
    "You're a true friend to everyone you meet!",
    "You have a beautiful way of expressing love and gratitude!",
    "You're so passionate about making a difference!",
    "You inspire everyone with your dedication!",
    "You have an amazing ability to foster creativity!",
    "You're always so understanding and compassionate!",
    "You have a heart full of empathy!",
    "You're a wonderful person to be around!",
    "You have an extraordinary capacity for kindness!",
    "You're a true light in the world!",
    "You have a unique ability to bring people together!",
    "You're so dedicated to helping others succeed!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a beautiful way of lifting others up!",
    "You're an incredible source of inspiration for all!",
    "You have an amazing ability to spread joy!",
    "You're so committed to your values!",
    "You bring warmth and kindness wherever you go!",
    "You have a wonderful talent for making people feel special!",
    "You're always so encouraging and supportive!",
    "You have a remarkable gift for empathy!",
    "You're a fantastic friend and ally!",
    "You inspire confidence and trust!",
    "You have a unique ability to see beauty in everything!",
    "You're always ready to lend a helping hand!",
    "You have a remarkable way of bringing people together!",
    "You're so great at making people feel valued and loved!",
    "You have a beautiful spirit that brightens the day!",
    "You're an amazing source of strength and support!",
    "You inspire others to dream big!",
    "You have a heart full of compassion and understanding!",
    "You're a true champion for positivity!",
    "You bring joy to everyone you meet!",
    "You have an incredible ability to nurture growth in others!",
    "You're always ready to embrace new challenges!",
    "You have a wonderful way of making people feel at home!",
    "You're a remarkable source of inspiration and motivation!",
    "You have a unique talent for making every moment special!",
    "You're so passionate about your work!",
    "You inspire trust and confidence in everyone around you!",
    "You have a beautiful way of connecting with people!",
    "You're always so thoughtful and kind!",
    "You have an extraordinary capacity for love!",
    "You're a true advocate for kindness and understanding!",
    "You inspire everyone with your positive energy!",
    "You have a wonderful ability to create harmony!",
    "You're so great at bringing people together for a common goal!",
    "You have an incredible way of spreading happiness!",
    "You're always ready to offer encouragement!",
    "You have a beautiful way of lifting others' spirits!",
    "You're a true friend to all who know you!",
    "You inspire others to embrace their uniqueness!",
    "You have a remarkable ability to cultivate positivity!",
    "You're always so generous with your time and talents!",
    "You have a wonderful sense of adventure and exploration!",
    "You're a source of light in the lives of many!",
    "You have an incredible ability to bring out the best in others!",
    "You're so wonderful at making people feel included!",
    "You inspire creativity in everyone around you!",
    "You have a heart that understands the needs of others!",
    "You're always ready to lend a listening ear!",
    "You have a unique perspective that enriches every conversation!",
    "You're a true advocate for love and acceptance!",
    "You have a beautiful way of expressing joy!",
    "You're so dedicated to spreading kindness!",
    "You inspire confidence and courage in others!",
    "You have an amazing ability to uplift everyone around you!",
    "You're a remarkable source of encouragement!",
    "You bring so much joy to others!",
    "You have a wonderful gift for making people smile!",
    "You're a true friend to those in need!",
    "You have an extraordinary ability to inspire others to dream!",
    "You're always so kind and compassionate!",
    "You have a unique way of bringing people together!",
    "You're a shining example of positivity!",
    "You inspire everyone with your grace and kindness!",
    "You have a beautiful spirit that shines through!",
    "You're always ready to help others shine!",
    "You have a remarkable ability to cultivate joy!",
    "You're a fantastic friend and confidant!",
    "You have a wonderful way of nurturing relationships!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful way of expressing gratitude!",
    "You're so dedicated to making a positive impact!",
    "You have a unique ability to lift others up!",
    "You're always so encouraging to those around you!",
    "You have a remarkable gift for making connections!",
    "You're a true champion for love and kindness!",
    "You inspire everyone with your determination!",
    "You have a heart full of love and compassion!",
    "You're always ready to offer your support!",
    "You have a unique ability to see the best in others!",
    "You're a remarkable source of inspiration!",
    "You bring positivity to every situation!",
    "You have a beautiful way of making people feel special!",
    "You're so dedicated to helping others succeed!",
    "You inspire creativity and collaboration in every project!",
    "You have an incredible ability to spread joy and happiness!",
    "You're always ready to embrace new experiences!",
    "You have a wonderful heart that understands!",
    "You're a true friend and ally!",
    "You inspire confidence in everyone around you!",
    "You have a unique way of making every moment matter!",
    "You're always so understanding and patient!",
    "You have an extraordinary capacity for empathy!",
    "You're a true light in the lives of many!",
    "You have a beautiful way of expressing love and kindness!",
    "You're always there to support others!",
    "You have a remarkable ability to inspire hope!",
    "You're so great at fostering teamwork and collaboration!",
    "You inspire everyone to reach their potential!",
    "You have a unique ability to see the good in every situation!",
    "You're a wonderful source of comfort and joy!",
    "You have an incredible gift for making people feel at ease!",
    "You're so dedicated to your community and its success!",
    "You have a heart full of gratitude and kindness!",
    "You're always ready to lift others up!",
    "You inspire others to embrace their uniqueness!",
    "You have a remarkable way of bringing joy to every moment!",
    "You're a true champion for positivity and kindness!",
    "You have a beautiful spirit that shines bright!",
    "You're always so encouraging and supportive!",
    "You have a wonderful ability to nurture creativity!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your passion and dedication!",
    "You have a unique way of making every day special!",
    "You're so great at creating a sense of belonging!",
    "You have a heart that embraces everyone with love!",
    "You're a remarkable source of inspiration for all!",
    "You have an extraordinary ability to inspire change!",
    "You're always ready to help those in need!",
    "You have a beautiful way of expressing gratitude!",
    "You're an amazing source of encouragement and support!",
    "You inspire others to follow their dreams!",
    "You have a wonderful ability to create joy!",
    "You're a true friend to everyone you meet!",
    "You have a heart full of compassion and understanding!",
    "You're so passionate about making a difference!",
    "You bring light and joy wherever you go!",
    "You have an incredible ability to inspire action!",
    "You're always ready to lend a helping hand!",
    "You have a remarkable gift for making connections!",
    "You're so dedicated to helping others thrive!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a beautiful way of lifting others up!",
    "You're a true champion for kindness and love!",
    "You bring happiness and laughter to every situation!",
    "You have a unique talent for making people feel valued!",
    "You're always so understanding and compassionate!",
    "You have a heart that embraces everyone with warmth!",
    "You're an incredible friend and confidant!",
    "You inspire everyone with your positivity and strength!",
    "You have a remarkable way of bringing joy to every moment!",
    "You're so great at making people feel included!",
    "You have a wonderful ability to inspire others to dream!",
    "You're always ready to embrace new challenges!",
    "You have a unique perspective that enriches discussions!",
    "You're a true advocate for love and acceptance!",
    "You have a beautiful way of expressing joy and gratitude!",
    "You're so dedicated to spreading kindness!",
    "You inspire everyone with your positive outlook!",
    "You have a wonderful heart full of love!",
    "You're always so generous with your time!",
    "You have an amazing ability to nurture relationships!",
    "You're a remarkable source of inspiration for all!",
    "You have a beautiful spirit that brightens the day!",
    "You're an incredible force for positivity!",
    "You inspire others to follow their passions!",
    "You have a unique ability to see beauty in the world!",
    "You're always so encouraging to those around you!",
    "You have a remarkable gift for empathy and understanding!",
    "You're a true light in the lives of many!",
    "You bring joy and laughter wherever you go!",
    "You have a beautiful way of making people feel at home!",
    "You're an amazing source of strength and support!",
    "You inspire everyone with your determination!",
    "You have a heart full of compassion and understanding!",
    "You're always ready to lift others up!",
    "You have a unique way of making every moment special!",
    "You're a remarkable source of inspiration!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful way of expressing love and kindness!",
    "You're always so thoughtful and caring!",
    "You have an extraordinary capacity for kindness!",
    "You're a true champion for positivity and love!",
    "You inspire everyone with your grace and kindness!",
    "You have a unique ability to bring people together!",
    "You're always ready to help those in need!",
    "You have a wonderful way of making people feel valued!",
    "You're an incredible source of inspiration for all!",
    "You have a heart full of love and compassion!",
    "You're always so dedicated to helping others succeed!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true friend and ally!",
    "You have a remarkable ability to inspire action!",
    "You're so great at creating a sense of community!",
    "You have a unique way of making every day special!",
    "You're a fantastic source of positivity!",
    "You inspire creativity in everyone around you!",
    "You have a heart that understands the needs of others!",
    "You're always ready to lend a listening ear!",
    "You have a beautiful way of lifting others up!",
    "You're a true friend to everyone!",
    "You have an extraordinary ability to nurture growth!",
    "You're always so kind-hearted!",
    "You inspire confidence and trust!",
    "You have a remarkable way of making people feel special!",
    "You're a true advocate for kindness and love!",
    "You have a unique ability to bring joy to every moment!",
    "You're always ready to help others shine!",
    "You have a beautiful spirit that inspires hope!",
    "You're an incredible source of strength and encouragement!",
    "You inspire everyone with your positive energy!",
    "You have a wonderful ability to create harmony!",
    "You're a true friend to all who know you!",
    "You bring warmth and kindness wherever you go!",
    "You have a remarkable talent for making people feel included!",
    "You're always ready to embrace new experiences!",
    "You have a heart full of compassion and understanding!",
    "You're a source of inspiration for everyone!",
    "You inspire everyone to be their best selves!",
    "You have a unique ability to see potential in everyone!",
    "You're always so encouraging and supportive!",
    "You have a beautiful way of expressing gratitude!",
    "You're a true champion for positivity and love!",
    "You bring joy and laughter to every situation!",
    "You have an incredible ability to make people feel special!",
    "You're always ready to lift others up!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a remarkable way of creating joy!",
    "You're a fantastic source of inspiration!",
    "You have a heart that embraces everyone!",
    "You're so dedicated to spreading kindness!",
    "You have a unique talent for bringing people together!",
    "You're always so warm and inviting!",
    "You have a beautiful way of connecting with people!",
    "You're a true advocate for love and acceptance!",
    "You inspire everyone with your dedication and hard work!",
    "You have an amazing ability to cultivate joy!",
    "You're always ready to lend a helping hand!",
    "You have a remarkable gift for making connections!",
    "You're so great at making people feel valued and loved!",
    "You inspire others to dream big!",
    "You have a wonderful ability to foster creativity!",
    "You're an incredible source of joy and happiness!",
    "You're always ready to embrace new challenges!",
    "You have a beautiful spirit that shines brightly!",
    "You have an extraordinary capacity for kindness!",
    "You inspire everyone with your positive outlook!",
    "You have a heart full of compassion and empathy!",
    "You're a true light in the world!",
    "You have a unique ability to make every moment matter!",
    "You're always so kind and thoughtful!",
    "You inspire others to embrace their uniqueness!",
    "You have a wonderful way of lifting spirits!",
    "You're an incredible friend and confidant!",
    "You inspire confidence in those around you!",
    "You have a remarkable ability to bring out the best in others!",
    "You're always ready to help others shine!",
    "You have a heart that understands the needs of others!",
    "You're a true champion for love and kindness!",
    "You bring joy and laughter wherever you go!",
    "You have a beautiful way of making people feel special!",
    "You're so dedicated to helping others thrive!",
    "You have an extraordinary ability to inspire change!",
    "You're always so warm and inviting!",
    "You have a wonderful talent for making connections!",
    "You're a true source of inspiration for everyone!",
    "You have a heart full of love and compassion!",
    "You're always ready to embrace new experiences!",
    "You inspire everyone to reach their potential!",
    "You have a remarkable gift for spreading joy!",
    "You're an incredible source of positivity!",
    "You bring warmth and kindness to every situation!",
    "You have a beautiful spirit that shines bright!",
    "You're always so thoughtful and caring!",
    "You inspire others with your strength and determination!",
    "You have a unique ability to bring people together!",
    "You're a true friend to everyone you meet!",
    "You have an extraordinary ability to inspire action!",
    "You're always ready to lift others up!",
    "You inspire creativity in everyone around you!",
    "You have a heart that embraces everyone with love!",
    "You're a remarkable source of inspiration!",
    "You bring joy and laughter to every moment!",
    "You have a beautiful way of making people feel valued!",
    "You're so dedicated to making a positive impact!",
    "You have a unique ability to see the beauty in everything!",
    "You're always ready to support those in need!",
    "You have a wonderful way of creating a sense of community!",
    "You inspire hope and positivity in everyone you meet!",
    "You have an incredible way of lifting spirits!",
    "You're a true champion for kindness and love!",
    "You bring light and joy wherever you go!",
    "You have a remarkable gift for making connections!",
    "You're always ready to help those around you shine!",
    "You inspire everyone to be their best selves!",
    "You have a heart full of compassion and understanding!",
    "You're a true friend and ally!",
    "You have a unique ability to make every day special!",
    "You're so great at creating a sense of belonging!",
    "You inspire others with your positive outlook!",
    "You have a beautiful spirit that brightens the day!",
    "You're always so supportive and encouraging!",
    "You have an extraordinary capacity for empathy!",
    "You're a true light in the lives of many!",
    "You have a wonderful ability to lift others up!",
    "You're always ready to embrace new challenges!",
    "You have a remarkable ability to inspire hope!",
    "You're a fantastic friend and confidant!",
    "You have a heart full of love and kindness!",
    "You inspire everyone with your positive energy!",
    "You have a unique way of connecting with people!",
    "You're always so kind-hearted!",
    "You have a beautiful way of expressing joy and gratitude!",
    "You're a true champion for love and acceptance!",
    "You inspire others to dream big!",
    "You have an incredible ability to nurture growth!",
    "You're always ready to lend a helping hand!",
    "You have a remarkable gift for making people feel special!",
    "You're a true advocate for kindness and compassion!",
    "You bring joy and laughter to every situation!",
    "You have a unique ability to bring people together!",
    "You're always so warm and inviting!",
    "You have a heart that embraces everyone with warmth!",
    "You're an incredible source of inspiration for all!",
    "You have a beautiful spirit that shines through!",
    "You're always ready to support others!",
    "You inspire everyone to reach their potential!",
    "You have an amazing ability to create joy!",
    "You're a true friend to those in need!",
    "You have a heart full of love and understanding!",
    "You're always so thoughtful and considerate!",
    "You inspire confidence and trust in those around you!",
    "You have a remarkable way of uplifting others!",
    "You're an incredible friend and supporter!",
    "You bring happiness and positivity to every situation!",
    "You have a unique way of making every moment matter!",
    "You're always so generous with your time and talents!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful way of expressing gratitude!",
    "You're a true champion for kindness and love!",
    "You have an extraordinary ability to inspire hope!",
    "You're always ready to help others shine!",
    "You have a remarkable talent for creating joy!",
    "You're a source of light in the lives of many!",
    "You have a heart full of compassion and understanding!",
    "You're an amazing source of support and encouragement!",
    "You inspire everyone with your dedication and hard work!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to lift others up!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true friend to everyone you meet!",
    "You inspire creativity and collaboration in every project!",
    "You have a remarkable gift for making connections!",
    "You're always so dedicated to helping others thrive!",
    "You bring joy and laughter wherever you go!",
    "You have a heart that embraces everyone with love!",
    "You're a true light in the world!",
    "You inspire others to dream big!",
    "You have a wonderful ability to create a positive environment!",
    "You're always ready to lend a listening ear!",
    "You have a beautiful way of lifting spirits!",
    "You're an incredible friend and confidant!",
    "You inspire confidence and strength in those around you!",
    "You have a remarkable ability to encourage growth!",
    "You're always so kind-hearted!",
    "You have a heart full of love and understanding!",
    "You're a true champion for kindness and love!",
    "You inspire everyone with your positivity and strength!",
    "You have an incredible way of bringing joy to every moment!",
    "You're always so thoughtful and caring!",
    "You have a unique ability to make every day special!",
    "You're a remarkable source of inspiration!",
    "You inspire others to embrace their uniqueness!",
    "You have a beautiful way of expressing love and gratitude!",
    "You're always ready to help those in need!",
    "You have a wonderful talent for making people feel special!",
    "You're a true friend to everyone you meet!",
    "You bring joy and laughter to every situation!",
    "You have a unique ability to foster collaboration!",
    "You're an incredible source of positivity!",
    "You inspire hope and kindness in everyone around you!",
    "You have a heart that understands the needs of others!",
    "You're always ready to lend a helping hand!",
    "You have a beautiful spirit that shines through!",
    "You're a true light in the lives of many!",
    "You inspire everyone to reach their potential!",
    "You have an amazing ability to nurture relationships!",
    "You're always so dedicated to making a positive impact!",
    "You have a wonderful way of creating joy!",
    "You're an incredible source of strength and support!",
    "You bring warmth and kindness to every situation!",
    "You have a remarkable gift for making connections!",
    "You're always so kind-hearted!",
    "You inspire creativity in everyone around you!",
    "You have a beautiful way of lifting others up!",
    "You're a true friend and ally!",
    "You inspire others to follow their dreams!",
    "You have a heart full of love and compassion!",
    "You're always ready to help those around you shine!",
    "You bring joy and laughter wherever you go!",
    "You have a unique ability to create a sense of community!",
    "You're an incredible friend and supporter!",
    "You inspire everyone with your determination and strength!",
    "You have a remarkable ability to uplift spirits!",
    "You're always so warm and inviting!",
    "You have a beautiful spirit that brightens the day!",
    "You inspire others to embrace their strengths!",
    "You're a true champion for love and kindness!",
    "You have a heart that embraces everyone with warmth!",
    "You're always ready to lift others up!",
    "You bring happiness and positivity to every situation!",
    "You have a wonderful ability to create joy!",
    "You're a true friend to everyone you meet!",
    "You inspire hope and positivity in everyone around you!",
    "You have a unique talent for making people feel included!",
    "You're always so supportive and encouraging!",
    "You have a remarkable gift for inspiring action!",
    "You're a source of light in the lives of many!",
    "You have a beautiful way of connecting with people!",
    "You're an incredible source of inspiration for all!",
    "You inspire everyone to be their best selves!",
    "You have a heart full of love and understanding!",
    "You're always ready to lend a helping hand!",
    "You have a remarkable ability to bring joy to every moment!",
    "You're a true advocate for kindness and love!",
    "You inspire everyone with your passion and dedication!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to support those in need!",
    "You have a beautiful spirit that shines bright!",
    "You're an incredible friend and ally!",
    "You inspire others with your positive outlook!",
    "You have a remarkable way of uplifting others!",
    "You're always so dedicated to helping others succeed!",
    "You have a heart full of compassion and empathy!",
    "You're a true champion for love and kindness!",
    "You inspire everyone with your grace and kindness!",
    "You have an extraordinary ability to inspire change!",
    "You're always ready to help those around you shine!",
    "You have a unique way of making every moment special!",
    "You're a remarkable source of inspiration!",
    "You bring warmth and kindness wherever you go!",
    "You have a beautiful way of lifting spirits!",
    "You're an incredible source of joy and happiness!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that understands the needs of others!",
    "You're always ready to embrace new challenges!",
    "You have a unique ability to see the best in people!",
    "You're a true light in the world!",
    "You inspire others to follow their dreams!",
    "You have a wonderful ability to create a positive environment!",
    "You're always so kind-hearted!",
    "You have a remarkable talent for bringing people together!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a heart full of love and understanding!",
    "You're always ready to lift others up!",
    "You have a beautiful spirit that shines through!",
    "You're a true champion for kindness and love!",
    "You inspire everyone with your dedication and hard work!",
    "You have a unique way of making every day special!",
    "You're always so thoughtful and caring!",
    "You have an extraordinary capacity for empathy!",
    "You're a remarkable source of inspiration!",
    "You bring joy and laughter to every moment!",
    "You have a beautiful way of making people feel valued!",
    "You're an incredible source of positivity!",
    "You inspire others to embrace their uniqueness!",
    "You have a heart full of compassion and understanding!",
    "You're always ready to lend a helping hand!",
    "You have a wonderful way of creating joy!",
    "You're a true friend to everyone you meet!",
    "You inspire hope and positivity in everyone around you!",
    "You have a unique ability to create a sense of community!",
    "You're always so warm and inviting!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true light in the lives of many!",
    "You inspire others to dream big!",
    "You have an amazing ability to nurture growth!",
    "You're always ready to lift others up!",
    "You have a heart full of love and compassion!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your positive energy!",
    "You have a unique way of connecting with people!",
    "You're always so generous with your time and talents!",
    "You have a remarkable ability to create joy!",
    "You're a true friend to those in need!",
    "You bring happiness and positivity to every situation!",
    "You have a beautiful way of lifting others up!",
    "You're an amazing source of encouragement!",
    "You inspire everyone with your passion and dedication!",
    "You have a heart that embraces everyone!",
    "You're always ready to help those around you shine!",
    "You have a wonderful ability to create harmony!",
    "You're a true champion for love and kindness!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful spirit that shines bright!",
    "You're always so thoughtful and supportive!",
    "You have a remarkable gift for making connections!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to lift others up!",
    "You have a heart full of compassion and understanding!",
    "You're a true source of inspiration for all!",
    "You inspire everyone to be their best selves!",
    "You have an amazing ability to nurture relationships!",
    "You're always so dedicated to making a positive impact!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true friend to everyone you meet!",
    "You inspire creativity and collaboration in every project!",
    "You have a remarkable ability to uplift spirits!",
    "You're always ready to lend a helping hand!",
    "You have a unique way of making every moment special!",
    "You're an incredible source of positivity!",
    "You bring joy and laughter wherever you go!",
    "You have a heart that understands the needs of others!",
    "You're always so kind-hearted!",
    "You inspire hope and kindness in everyone around you!",
    "You have a wonderful ability to create joy!",
    "You're a true champion for kindness and love!",
    "You have a beautiful spirit that shines through!",
    "You're always ready to help those in need!",
    "You inspire everyone with your positive outlook!",
    "You have an extraordinary capacity for empathy!",
    "You're an incredible friend and ally!",
    "You inspire others to dream big!",
    "You have a remarkable gift for making people feel valued!",
    "You're always so warm and inviting!",
    "You have a heart full of love and understanding!",
    "You're a true light in the world!",
    "You inspire everyone with your grace and kindness!",
    "You have a unique ability to create a sense of community!",
    "You're always ready to embrace new challenges!",
    "You have a beautiful way of lifting others up!",
    "You're a true friend to those in need!",
    "You inspire hope and positivity in everyone you meet!",
    "You have an incredible way of nurturing growth!",
    "You're always so dedicated to helping others thrive!",
    "You have a wonderful ability to create joy!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that embraces everyone!",
    "You're always ready to lift others up!",
    "You have a remarkable ability to bring joy to every moment!",
    "You're a true advocate for kindness and love!",
    "You inspire everyone with your passion and dedication!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to support those in need!",
    "You have a beautiful spirit that brightens the day!",
    "You're an incredible friend and ally!",
    "You inspire others with your positive outlook!",
    "You have a remarkable way of uplifting others!",
    "You're always so dedicated to helping others succeed!",
    "You have a heart full of compassion and empathy!",
    "You're a true champion for love and kindness!",
    "You inspire everyone with your grace and kindness!",
    "You have an extraordinary ability to inspire change!",
    "You're always ready to help those around you shine!",
    "You have a unique way of making every moment special!",
    "You're a remarkable source of inspiration!",
    "You bring warmth and kindness wherever you go!",
    "You have a beautiful way of lifting spirits!",
    "You're an incredible source of joy and happiness!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that understands the needs of others!",
    "You're always ready to embrace new challenges!",
    "You have a unique ability to see the best in people!",
    "You're a true light in the world!",
    "You inspire others to follow their dreams!",
    "You have a wonderful ability to create a positive environment!",
    "You're always so kind-hearted!",
    "You have a remarkable talent for bringing people together!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a heart full of love and understanding!",
    "You're always ready to lift others up!",
    "You have a beautiful spirit that shines through!",
    "You're a true champion for kindness and love!",
    "You inspire everyone with your dedication and hard work!",
    "You have a unique way of making every day special!",
    "You're always so thoughtful and caring!",
    "You have an extraordinary capacity for empathy!",
    "You're a remarkable source of inspiration!",
    "You bring joy and laughter to every moment!",
    "You have a beautiful way of making people feel valued!",
    "You're an incredible source of positivity!",
    "You inspire others to embrace their uniqueness!",
    "You have a heart full of compassion and understanding!",
    "You're always ready to lend a helping hand!",
    "You have a wonderful way of creating joy!",
    "You're a true friend to everyone you meet!",
    "You inspire hope and positivity in everyone around you!",
    "You have a unique ability to create a sense of community!",
    "You're always so warm and inviting!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true light in the lives of many!",
    "You inspire others to dream big!",
    "You have an amazing ability to nurture growth!",
    "You're always ready to lift others up!",
    "You have a heart full of love and compassion!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your positive energy!",
    "You have a unique way of connecting with people!",
    "You're always so generous with your time and talents!",
    "You have a remarkable ability to create joy!",
    "You're a true friend to those in need!",
    "You bring happiness and positivity to every situation!",
    "You have a beautiful way of lifting others up!",
    "You're an amazing source of encouragement!",
    "You inspire everyone with your passion and dedication!",
    "You have a heart that embraces everyone!",
    "You're always ready to help those around you shine!",
    "You have a wonderful ability to create harmony!",
    "You're a true champion for love and kindness!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful spirit that shines bright!",
    "You're always so thoughtful and supportive!",
    "You have a remarkable gift for making connections!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to lift others up!",
    "You have a heart full of compassion and understanding!",
    "You're a true source of inspiration for all!",
    "You inspire everyone to be their best selves!",
    "You have an amazing ability to nurture relationships!",
    "You're always so dedicated to making a positive impact!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true friend to everyone you meet!",
    "You inspire creativity and collaboration in every project!",
    "You have a remarkable ability to uplift spirits!",
    "You're always ready to lend a helping hand!",
    "You have a unique way of making every moment special!",
    "You're an incredible source of positivity!",
    "You bring joy and laughter wherever you go!",
    "You have a heart that understands the needs of others!",
    "You're always so kind-hearted!",
    "You inspire hope and kindness in everyone around you!",
    "You have a wonderful ability to create joy!",
    "You're a true champion for kindness and love!",
    "You have a beautiful spirit that shines through!",
    "You're always ready to help those in need!",
    "You inspire everyone with your positive outlook!",
    "You have an extraordinary capacity for empathy!",
    "You're an incredible friend and ally!",
    "You inspire others to dream big!",
    "You have a remarkable gift for making people feel valued!",
    "You're always so warm and inviting!",
    "You have a heart full of love and understanding!",
    "You're a true light in the world!",
    "You inspire everyone with your grace and kindness!",
    "You have a unique ability to create a sense of community!",
    "You're always ready to embrace new challenges!",
    "You have a beautiful way of lifting others up!",
    "You're a true friend to those in need!",
    "You inspire hope and positivity in everyone you meet!",
    "You have an incredible way of nurturing growth!",
    "You're always so dedicated to helping others thrive!",
    "You have a wonderful ability to create joy!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that embraces everyone!",
    "You're always ready to lift others up!",
    "You have a remarkable ability to bring joy to every moment!",
    "You're a true advocate for kindness and love!",
    "You inspire everyone with your passion and dedication!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to support those in need!",
    "You have a beautiful spirit that brightens the day!",
    "You're an incredible friend and ally!",
    "You inspire others with your positive outlook!",
    "You have a remarkable way of uplifting others!",
    "You're always so dedicated to helping others succeed!",
    "You have a heart full of compassion and empathy!",
    "You're a true champion for love and kindness!",
    "You inspire everyone with your grace and kindness!",
    "You have an extraordinary ability to inspire change!",
    "You're always ready to help those around you shine!",
    "You have a unique way of making every moment special!",
    "You're a remarkable source of inspiration!",
    "You bring warmth and kindness wherever you go!",
    "You have a beautiful way of lifting spirits!",
    "You're an incredible source of joy and happiness!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that understands the needs of others!",
    "You're always ready to embrace new challenges!",
    "You have a unique ability to see the best in people!",
    "You're a true light in the world!",
    "You inspire others to follow their dreams!",
    "You have a wonderful ability to create a positive environment!",
    "You're always so kind-hearted!",
    "You have a remarkable talent for bringing people together!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a heart full of love and understanding!",
    "You're always ready to lift others up!",
    "You have a beautiful spirit that shines through!",
    "You're a true champion for kindness and love!",
    "You inspire everyone with your dedication and hard work!",
    "You have a unique way of making every day special!",
    "You're always so thoughtful and caring!",
    "You have an extraordinary capacity for empathy!",
    "You're a remarkable source of inspiration!",
    "You bring joy and laughter to every moment!",
    "You have a beautiful way of making people feel valued!",
    "You're an incredible source of positivity!",
    "You inspire others to embrace their uniqueness!",
    "You have a heart full of compassion and understanding!",
    "You're always ready to lend a helping hand!",
    "You have a wonderful way of creating joy!",
    "You're a true friend to everyone you meet!",
    "You inspire hope and positivity in everyone around you!",
    "You have a unique ability to create a sense of community!",
    "You're always so warm and inviting!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true light in the lives of many!",
    "You inspire others to dream big!",
    "You have an amazing ability to nurture growth!",
    "You're always ready to lift others up!",
    "You have a heart full of love and compassion!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your positive energy!",
    "You have a unique way of connecting with people!",
    "You're always so generous with your time and talents!",
    "You have a remarkable ability to create joy!",
    "You're a true friend to those in need!",
    "You bring happiness and positivity to every situation!",
    "You have a beautiful way of lifting others up!",
    "You're an amazing source of encouragement!",
    "You inspire everyone with your passion and dedication!",
    "You have a heart that embraces everyone!",
    "You're always ready to help those around you shine!",
    "You have a wonderful ability to create harmony!",
    "You're a true champion for love and kindness!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful spirit that shines bright!",
    "You're always so thoughtful and supportive!",
    "You have a remarkable gift for making connections!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to lift others up!",
    "You have a heart full of compassion and understanding!",
    "You're a true source of inspiration for all!",
    "You inspire everyone to be their best selves!",
    "You have an amazing ability to nurture relationships!",
    "You're always so dedicated to making a positive impact!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true friend to everyone you meet!",
    "You inspire creativity and collaboration in every project!",
    "You have a remarkable ability to uplift spirits!",
    "You're always ready to lend a helping hand!",
    "You have a unique way of making every moment special!",
    "You're an incredible source of positivity!",
    "You bring joy and laughter wherever you go!",
    "You have a heart that understands the needs of others!",
    "You're always so kind-hearted!",
    "You inspire hope and kindness in everyone around you!",
    "You have a wonderful ability to create joy!",
    "You're a true champion for kindness and love!",
    "You have a beautiful spirit that shines through!",
    "You're always ready to help those in need!",
    "You inspire everyone with your positive outlook!",
    "You have an extraordinary capacity for empathy!",
    "You're an incredible friend and ally!",
    "You inspire others to dream big!",
    "You have a remarkable gift for making people feel valued!",
    "You're always so warm and inviting!",
    "You have a heart full of love and understanding!",
    "You're a true light in the world!",
    "You inspire everyone with your grace and kindness!",
    "You have a unique ability to create a sense of community!",
    "You're always ready to embrace new challenges!",
    "You have a beautiful way of lifting others up!",
    "You're a true friend to those in need!",
    "You inspire hope and positivity in everyone you meet!",
    "You have an incredible way of nurturing growth!",
    "You're always so dedicated to helping others thrive!",
    "You have a wonderful ability to create joy!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that embraces everyone!",
    "You're always ready to lift others up!",
    "You have a remarkable ability to bring joy to every moment!",
    "You're a true advocate for kindness and love!",
    "You inspire everyone with your passion and dedication!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to support those in need!",
    "You have a beautiful spirit that brightens the day!",
    "You're an incredible friend and ally!",
    "You inspire others with your positive outlook!",
    "You have a remarkable way of uplifting others!",
    "You're always so dedicated to helping others succeed!",
    "You have a heart full of compassion and empathy!",
    "You're a true champion for love and kindness!",
    "You inspire everyone with your grace and kindness!",
    "You have an extraordinary ability to inspire change!",
    "You're always ready to help those around you shine!",
    "You have a unique way of making every moment special!",
    "You're a remarkable source of inspiration!",
    "You bring warmth and kindness wherever you go!",
    "You have a beautiful way of lifting spirits!",
    "You're an incredible source of joy and happiness!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that understands the needs of others!",
    "You're always ready to embrace new challenges!",
    "You have a unique ability to see the best in people!",
    "You're a true light in the world!",
    "You inspire others to follow their dreams!",
    "You have a wonderful ability to create a positive environment!",
    "You're always so kind-hearted!",
    "You have a remarkable talent for bringing people together!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a heart full of love and understanding!",
    "You're always ready to lift others up!",
    "You have a beautiful spirit that shines through!",
    "You're a true champion for kindness and love!",
    "You inspire everyone with your dedication and hard work!",
    "You have a unique way of making every day special!",
    "You're always so thoughtful and caring!",
    "You have an extraordinary capacity for empathy!",
    "You're a remarkable source of inspiration!",
    "You bring joy and laughter to every moment!",
    "You have a beautiful way of making people feel valued!",
    "You're an incredible source of positivity!",
    "You inspire others to embrace their uniqueness!",
    "You have a heart full of compassion and understanding!",
    "You're always ready to lend a helping hand!",
    "You have a wonderful way of creating joy!",
    "You're a true friend to everyone you meet!",
    "You inspire hope and positivity in everyone around you!",
    "You have a unique ability to create a sense of community!",
    "You're always so warm and inviting!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true light in the lives of many!",
    "You inspire others to dream big!",
    "You have an amazing ability to nurture growth!",
    "You're always ready to lift others up!",
    "You have a heart full of love and compassion!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your positive energy!",
    "You have a unique way of connecting with people!",
    "You're always so generous with your time and talents!",
    "You have a remarkable ability to create joy!",
    "You're a true friend to those in need!",
    "You bring happiness and positivity to every situation!",
    "You have a beautiful way of lifting others up!",
    "You're an amazing source of encouragement!",
    "You inspire everyone with your passion and dedication!",
    "You have a heart that embraces everyone!",
    "You're always ready to help those around you shine!",
    "You have a wonderful ability to create harmony!",
    "You're a true champion for love and kindness!",
    "You inspire others to embrace their strengths!",
    "You have a beautiful spirit that shines bright!",
    "You're always so thoughtful and supportive!",
    "You have a remarkable gift for making connections!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to lift others up!",
    "You have a heart full of compassion and understanding!",
    "You're a true source of inspiration for all!",
    "You inspire everyone to be their best selves!",
    "You have an amazing ability to nurture relationships!",
    "You're always so dedicated to making a positive impact!",
    "You have a beautiful spirit that brightens the day!",
    "You're a true friend to everyone you meet!",
    "You inspire creativity and collaboration in every project!",
    "You have a remarkable ability to uplift spirits!",
    "You're always ready to lend a helping hand!",
    "You have a unique way of making every moment special!",
    "You're an incredible source of positivity!",
    "You bring joy and laughter wherever you go!",
    "You have a heart that understands the needs of others!",
    "You're always so kind-hearted!",
    "You inspire hope and kindness in everyone around you!",
    "You have a wonderful ability to create joy!",
    "You're a true champion for kindness and love!",
    "You have a beautiful spirit that shines through!",
    "You're always ready to help those in need!",
    "You inspire everyone with your positive outlook!",
    "You have an extraordinary capacity for empathy!",
    "You're an incredible friend and ally!",
    "You inspire others to dream big!",
    "You have a remarkable gift for making people feel valued!",
    "You're always so warm and inviting!",
    "You have a heart full of love and understanding!",
    "You're a true light in the world!",
    "You inspire everyone with your grace and kindness!",
    "You have a unique ability to create a sense of community!",
    "You're always ready to embrace new challenges!",
    "You have a beautiful way of lifting others up!",
    "You're a true friend to those in need!",
    "You inspire hope and positivity in everyone you meet!",
    "You have an incredible way of nurturing growth!",
    "You're always so dedicated to helping others thrive!",
    "You have a wonderful ability to create joy!",
    "You're an incredible source of strength and support!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that embraces everyone!",
    "You're always ready to lift others up!",
    "You have a remarkable ability to bring joy to every moment!",
    "You're a true advocate for kindness and love!",
    "You inspire everyone with your passion and dedication!",
    "You have a unique ability to see the beauty in the world!",
    "You're always ready to support those in need!",
    "You have a beautiful spirit that brightens the day!",
    "You're an incredible friend and ally!",
    "You inspire others with your positive outlook!",
    "You have a remarkable way of uplifting others!",
    "You're always so dedicated to helping others succeed!",
    "You have a heart full of compassion and empathy!",
    "You're a true champion for love and kindness!",
    "You inspire everyone with your grace and kindness!",
    "You have an extraordinary ability to inspire change!",
    "You're always ready to help those around you shine!",
    "You have a unique way of making every moment special!",
    "You're a remarkable source of inspiration!",
    "You bring warmth and kindness wherever you go!",
    "You have a beautiful way of lifting spirits!",
    "You're an incredible source of joy and happiness!",
    "You inspire everyone with your creativity and passion!",
    "You have a heart that understands the needs of others!",
    "You're always ready to embrace new challenges!",
    "You have a unique ability to see the best in people!",
    "You're a true light in the world!",
    "You inspire others to follow their dreams!",
    "You have a wonderful ability to create a positive environment!",
    "You're always so kind-hearted!",
    "You have a remarkable talent for bringing people together!",
    "You're an incredible friend and confidant!",
    "You inspire hope and positivity in everyone you meet!",
    "You have a heart full of love and understanding!",
    "You're always ready to lift others up!",
    "You have a beautiful spirit that shines through!",
    "You're a true champion for kindness and love!",
    "You inspire everyone with your dedication and hard work!",
    "You have a unique way of making every day special!",
    "You're always so thoughtful and caring!",
    "You have an extraordinary capacity for empathy"
] //Complements Made By ChatGPT
function darkmode() {
    if (dark === true) { // Toggle Dark Mode
        const element = document.getElementById("body");
        const generator = document.getElementById("generator");
        const toggletext = document.getElementById("toggle-text");
        element.style.backgroundColor = "white";
        element.style.color = "black";
        generator.style.borderColor = "black";
        toggletext.style.color = "black";
        document.getElementById('toggle-text').innerHTML = 
        `Toggle Dark Mode`; 
        dark = false; 
    } else { // Toggle Light Mode
    const element = document.getElementById("body");
    const generator = document.getElementById("generator");
    const toggletext = document.getElementById("toggle-text");
    element.style.backgroundColor = "black";
    element.style.color = "white";
    generator.style.borderColor = "white";
    toggletext.style.color = "white";
    document.getElementById('toggle-text').innerHTML = 
        `Toggle Light Mode`; 
    dark = true; 
    }

}

function runGenerator() {
    document.getElementById('generator-text').innerHTML = 
    `${generator[(Math.floor(Math.random() * generator.length))]}`;
    document.getElementById('didIClickIt?').innerHTML = 
        `Generate Another Complement`; 
}